version: "2.1"
services:
    odoo:
        build:
            context: ./odoo
            args:
                PGUSER: "$DB_USER"
                PGPASSWORD: "$DB_PASSWORD"
        tty: true
        volumes:
            - filestore$ODOO_MAJOR:/var/lib/odoo
        networks:
            default:
                aliases:
                    # For `https` service
                    - www

    db:
        image: postgres:${DB_VERSION}-alpine
        environment:
            POSTGRES_USER: "$DB_USER"
            POSTGRES_PASSWORD: "$DB_PASSWORD"
        volumes:
            - db$ODOO_MAJOR:/var/lib/postgresql/data

    # TODO Remove this when Traefik 1.3 is released
    # SEE https://github.com/containous/traefik/pull/1257
    proxy:
        image: tecnativa/odoo-proxy
        environment:
            FORWARDFOR: 0
        labels:
            traefik.docker.network: "inverseproxy_shared"
            traefik.enable: "true"
            traefik.frontend.passHostHeader: "true"
            traefik.port: "80"

    smtpfake:
        image: tecnativa/smtp-sink

    smtpreal:
        image: tecnativa/postfix-relay
        volumes:
            - smtp:/var/spool/postfix
        environment:
            MAILNAME: "$SMTP_REAL_MAILNAME"
            MAIL_RELAY_HOST: "$SMTP_REAL_RELAY_HOST"
            MAIL_RELAY_PORT: "$SMTP_REAL_RELAY_PORT"
            MAIL_RELAY_USER: "$SMTP_REAL_RELAY_USER"
            MAIL_RELAY_PASS: "$SMTP_REAL_RELAY_PASS"
            MAIL_CANONICAL_DOMAINS: "$SMTP_REAL_CANONICAL_DOMAINS"
            MAIL_NON_CANONICAL_DEFAULT: "$SMTP_REAL_NON_CANONICAL_DEFAULT"

    inboxfake:
        image: tecnativa/tcp-proxy
        environment:
            LISTEN: "$INBOX_FAKE_LISTEN"
            TALK: "$INBOX_FAKE_TALK"

    inboxreal:
        image: tecnativa/tcp-proxy
        environment:
            LISTEN: "$INBOX_REAL_LISTEN"
            TALK: "$INBOX_REAL_TALK"

    backup:
        image: tecnativa/server-backup
        environment:
            MAIL_RELAY_HOST: smtp
            ROOT_EMAIL_FROM: "$BACKUP_ROOT_EMAIL_FROM"
            ROOT_EMAIL_TO: "$BACKUP_ROOT_EMAIL_TO"
            BACKUP_S3_ACCESS_KEY: "$BACKUP_S3_ACCESS_KEY"
            BACKUP_S3_SECRET_KEY: "$BACKUP_S3_SECRET_KEY"
            BACKUP_S3_BUCKET: "$BACKUP_S3_BUCKET"
            BACKUP_S3_INSTANCE: "$BACKUP_S3_INSTANCE"
            BACKUP_SEND_MAIL_ERR: "$BACKUP_SEND_MAIL_ERR"
            BACKUP_SEND_MAIL_LOG: "$BACKUP_SEND_MAIL_LOG"
            BACKUP_EMAIL_SUBJECT: "$BACKUP_EMAIL_SUBJECT"
            BACKUP_EMAIL_FROM: "$BACKUP_EMAIL_FROM"
            BACKUP_EMAIL_TO: "$BACKUP_EMAIL_TO"
            BACKUP_ENCRYPT: "$BACKUP_ENCRYPT"
            BACKUP_ENCRYPT_KEY: "$BACKUP_ENCRYPT_KEY"
            BACKUP_SOURCES: /var/lib/odoo,0,1
            PG_HOST: db
            PG_USER: "$DB_USER"
            PG_PASS: "$DB_PASSWORD"
        volumes:
            - filestore$ODOO_MAJOR:/var/lib/odoo
